In [1]:
# Import summarize from gensim
from gensim.summarization.summarizer import summarize
from gensim.summarization import keywords

In [2]:
# To convert MSword doc to txt for processing
import docx2txt

In [3]:
resume = docx2txt.process('/Users/akanshyameher/Desktop/Applicant1.docx')

In [4]:
#Summarizing resume 
text_resume = str(resume)
resume2 = summarize(text_resume, ratio=0.1)
print(resume2)

With degrees in Computer Science and Data Analytics, equipping me with programming and analysis skills and experience to deal with large plus complex datasets.
Implementing ML elements to provide regression related trends and analysis to potentially test devices on athletes to capture data and build relevant datasets.
Data Analyst Consultant | UCF College of Engineering and Computer Science | Orlando, FL	                  Aug 2020 – Present
Relevant Coursework                  Database Systems, Data Preparation, Network Science, Statistical Analysis, Interactive Data Visualization, Machine Learning, Data Mining, Advanced Text Mining, Parallel and Cloud Computing, Data Structures and Algorithms, Business Intelligence and its Applications
Introduction to Data Analytics for Business by University of Colorado Boulder | Coursera
Built a binary classification model using Machine Learning to predict Diabetes in the United States using Python.


In [5]:
#Prompt for the Job description.
jd = input("Enter the job description: ")  

Enter the job description: o	Collecting the data from multiple heterogeneous data sources. o	Check the actual nature of the data by conducting preliminary data analysis. o	Conduct the thorough analysis of data to check for meaningful data. o	Perform data mining with using different querying techniques of SQL. o	Check for different data configurations and patterns. o	Help the senior management for decision making by representing the data with using different representational techniques like Graphs charts. o	Model the data with using different modeling techniques. o	Make the projections of the data according to analyzing the trends of data. o	Create different kind of reports with using different Business Intelligence tools like OBIEE or Tableau. o	Present your findings with good presentation through meetings, seminars and presentations. o	Preparing the report which will give information about all the data which will helps the senior management. o	Discuss with senior management about the 

In [6]:
#Count Vectorizer 
text_list = [resume2, jd]
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
count_matrix = cv.fit_transform(text_list)

In [7]:
from sklearn.metrics.pairwise import cosine_similarity
matchPercentage = cosine_similarity(count_matrix)
print(matchPercentage)

[[1.         0.46436605]
 [0.46436605 1.        ]]


In [8]:
# get the match percentage
matchPercentage = cosine_similarity(count_matrix)[0][1] * 100
matchPercentage = round(matchPercentage, 2) 
print("Your resume matches about "+ str(matchPercentage)+ "% of the job description.")

Your resume matches about 46.44% of the job description.


In [9]:
#important keywords of the job description
a = keywords(jd, ratio=0.7)
a

'data\nlike\ndifferent querying techniques\nbusiness\nanalysis\ngraphs\ngood presentation\npresent\npresentations\nmeetings seminars\nsenior management\ndecision making\nactual nature\nintelligence tools\nmodel\nmodeling\nrepresentational\nmultiple heterogeneous\nconducting preliminary\nconduct\nthorough'

In [10]:
b = keywords(resume2, ratio =0.7)
b

'data\nrelevant\ndatasets\nmining\nbusiness\nclassification\nscience\nanalysis\nboulder\ncoursera\nregression related\npotentially test\nucf\npresent\nplus complex\nconsultant\npredict\nstates\nunited\nintroduction\ndiabetes\napplications\nanalytics\ncomputing\nstatistical\nnetwork\ncoursework\nanalyst\ndatabase\nmachine\ninteractive\npreparation\nsystems\nadvanced\ntext\nlearning\nvisualization\nintelligence\nalgorithms'

In [11]:
c = []
for i in a.split('\n'):
    for j in i.split(' '):
        c.append(j)
print(c)        

['data', 'like', 'different', 'querying', 'techniques', 'business', 'analysis', 'graphs', 'good', 'presentation', 'present', 'presentations', 'meetings', 'seminars', 'senior', 'management', 'decision', 'making', 'actual', 'nature', 'intelligence', 'tools', 'model', 'modeling', 'representational', 'multiple', 'heterogeneous', 'conducting', 'preliminary', 'conduct', 'thorough']


In [12]:
d = []
for i in b.split('\n'):
    for j in i.split(' '):
        d.append(j)
print(d)

['data', 'relevant', 'datasets', 'mining', 'business', 'classification', 'science', 'analysis', 'boulder', 'coursera', 'regression', 'related', 'potentially', 'test', 'ucf', 'present', 'plus', 'complex', 'consultant', 'predict', 'states', 'united', 'introduction', 'diabetes', 'applications', 'analytics', 'computing', 'statistical', 'network', 'coursework', 'analyst', 'database', 'machine', 'interactive', 'preparation', 'systems', 'advanced', 'text', 'learning', 'visualization', 'intelligence', 'algorithms']


In [13]:
present = []
absent = []
for i in c:
    if i in d:
        present.append(i) 
    else:
        absent.append(i)
print("Present words are: ", present)
print("Absent words are: ", absent)

Present words are:  ['data', 'business', 'analysis', 'present', 'intelligence']
Absent words are:  ['like', 'different', 'querying', 'techniques', 'graphs', 'good', 'presentation', 'presentations', 'meetings', 'seminars', 'senior', 'management', 'decision', 'making', 'actual', 'nature', 'tools', 'model', 'modeling', 'representational', 'multiple', 'heterogeneous', 'conducting', 'preliminary', 'conduct', 'thorough']


In [14]:
def jaccard_distance(resume2,jd):
    intersection=len(set.intersection(*[set(resume2),set(jd)]))
    union=len(set.union(*[set(resume2),set(jd)]))
    return intersection/float(union)
b=jaccard_distance(resume2,jd) 

print('\n  Jaccard  :  ', b)  


  Jaccard  :   0.6964285714285714


In [15]:
resume = docx2txt.process('/Users/akanshyameher/Desktop/Applicant2.docx')

In [16]:
#Summarizing resume 
text_resume = str(resume)
resume2 = summarize(text_resume, ratio=0.1)
print(resume2)

Coursework/Other: Statistical Analysis, Machine Learning, Data Visualization, Data Preparation, Data Mining, Advance Data Mining, Text Mining, Parallel and Cloud Computing, Artificial Intelligence, Recommendation Systems, Time Series Analysis and Forecasting, Data Structure, RDBMS
UCF Ranking Prediction and Inference	Aug 2020 - Present
Predicting the UCF world ranking and identifying factors influencing the ranking by building model using Decision trees, linear models, feature engineering and presented in Tableau
Recognition of drunk person using Machine Learning (Team Members 4)	Jun 2017 - Jun 2018


In [17]:
#Prompt for the Job description.
jd = input("Enter the job description: ")  

Enter the job description: o	Collecting the data from multiple heterogeneous data sources. o	Check the actual nature of the data by conducting preliminary data analysis. o	Conduct the thorough analysis of data to check for meaningful data. o	Perform data mining with using different querying techniques of SQL. o	Check for different data configurations and patterns. o	Help the senior management for decision making by representing the data with using different representational techniques like Graphs charts. o	Model the data with using different modeling techniques. o	Make the projections of the data according to analyzing the trends of data. o	Create different kind of reports with using different Business Intelligence tools like OBIEE or Tableau. o	Present your findings with good presentation through meetings, seminars and presentations. o	Preparing the report which will give information about all the data which will helps the senior management. o	Discuss with senior management about the 

In [18]:
#Count Vectorizer 
text_list = [resume2, jd]
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
count_matrix = cv.fit_transform(text_list)

In [19]:
from sklearn.metrics.pairwise import cosine_similarity
matchPercentage = cosine_similarity(count_matrix)
print(matchPercentage)

[[1.         0.43882879]
 [0.43882879 1.        ]]


In [20]:
# get the match percentage
matchPercentage = cosine_similarity(count_matrix)[0][1] * 100
matchPercentage = round(matchPercentage, 2) 
print("Your resume matches about "+ str(matchPercentage)+ "% of the job description.")

Your resume matches about 43.88% of the job description.


In [21]:
print(keywords(resume2, ratio =0.5))

data
mining
model
factors
analysis
models feature
learning
ranking
ucf
computing
trees linear
aug
artificial
intelligence
present
presented
recommendation
systems
drunk person
tableau
recognition
time


In [22]:
def jaccard_distance(resume2,jd):
    intersection=len(set.intersection(*[set(resume2),set(jd)]))
    union=len(set.union(*[set(resume2),set(jd)]))
    return intersection/float(union)
b=jaccard_distance(resume2,jd) 

print('\n  Jaccard  :  ', b)  


  Jaccard  :   0.5806451612903226


In [23]:
resume = docx2txt.process('/Users/akanshyameher/Desktop/Applicant3.docx')

In [24]:
#Summarizing resume 
text_resume = str(resume)
resume2 = summarize(text_resume, ratio=0.1)
print(resume2)

Highly analytical individual with strong apt for learning and collaborative skills, also coming with strong interpersonal, leadership, and programming abilities, looking to obtain a position in Data Science field, to utilize my academic knowledge and prior internships experience.
Visualized the effect of sentiment through wordclouds, Bing comparison cloud and bar charts and concluded ‘Deathly Hallows’ & ‘Half Blood Prince’ had  highest negative and positive scores respectively
Analyzed and cleaned data to drive process improvements within the organization using Excel
Utilized Tableau to produce appealing data visualizations related to web- analytics, call-center technology, sales and marketing to help them make business decisions
Programming: Python (NumPy, Pandas, Scikit-Learn, Matplotlib, Seaborn, Folium), SQL, R, PySpark, SAS, Hive, Java, C, C++ Analytics and Visualization Tools: Tableau, GGplot, Advance MS Excel, IBM Cloud Studio, Apache Zeppelin


In [25]:
#Prompt for the Job description.
jd = input("Enter the job description: ")  

Enter the job description: o	Collecting the data from multiple heterogeneous data sources. o	Check the actual nature of the data by conducting preliminary data analysis. o	Conduct the thorough analysis of data to check for meaningful data. o	Perform data mining with using different querying techniques of SQL. o	Check for different data configurations and patterns. o	Help the senior management for decision making by representing the data with using different representational techniques like Graphs charts. o	Model the data with using different modeling techniques. o	Make the projections of the data according to analyzing the trends of data. o	Create different kind of reports with using different Business Intelligence tools like OBIEE or Tableau. o	Present your findings with good presentation through meetings, seminars and presentations. o	Preparing the report which will give information about all the data which will helps the senior management. o	Discuss with senior management about the 

In [26]:
#Count Vectorizer 
text_list = [resume2, jd]
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
count_matrix = cv.fit_transform(text_list)

In [27]:
from sklearn.metrics.pairwise import cosine_similarity
matchPercentage = cosine_similarity(count_matrix)
print(matchPercentage)

[[1.         0.33287321]
 [0.33287321 1.        ]]


In [28]:
# get the match percentage
matchPercentage = cosine_similarity(count_matrix)[0][1] * 100
matchPercentage = round(matchPercentage, 2) 
print("Your resume matches about "+ str(matchPercentage)+ "% of the job description.")

Your resume matches about 33.29% of the job description.


In [29]:
print(keywords(resume2, ratio =0.5))

data
analytical
analytics
visualized
visualizations
visualization
programming
technology
process
tableau
sas
hive
scores respectively
interpersonal
strong
bing comparison cloud
deathly
blood
folium
hallows
half
apache
internships
abilities
decisions
seaborn
appealing
science
ggplot
matplotlib
studio
learning
experience
scikit
pandas
python
numpy


In [30]:
def jaccard_distance(resume2,jd):
    intersection=len(set.intersection(*[set(resume2),set(jd)]))
    union=len(set.union(*[set(resume2),set(jd)]))
    return intersection/float(union)
b=jaccard_distance(resume2,jd) 

print('\n  Jaccard  :  ', b)  


  Jaccard  :   0.639344262295082


In [31]:
resume = docx2txt.process('/Users/akanshyameher/Desktop/Applicant4.docx')

In [32]:
#Summarizing resume 
text_resume = str(resume)
resume2 = summarize(text_resume, ratio=0.1)
print(resume2)

Implement machine learning elements to provide regression/progression related trends and analysis.
Data Analyst Consultant (Capstone Project) | University of Central Florida |Orlando, FL	Aug 2020 – Present
Analyzing ten years of US News and World Report ranking data, and predicting the future ranking of the University of Central Florida for the UCF engineering department.
Relevant Coursework	Natural Language Processing, Machine Learning, Data Mining, Data Visualization, Statistics, Network Sciences, Data Preparation, Data Mining II, Text mining, Parallel and Cloud Computation, Artificial Intelligence, Programming in Java, Big Data, Database Management System, Linear Algebra, Data Structure, Algorithm design and analysis, Object oriented programming in C++, Introduction to C programming,, Engineering Mathematics, Unified Modeling Language, Probability and Statistics, Operating System, Theory of Computation, Computer Architecture.
Developed a supervised machine learning model using the L

In [33]:
#Prompts for the Job description.
jd = input("Enter the job description: ")  

Enter the job description: o	Collecting the data from multiple heterogeneous data sources. o	Check the actual nature of the data by conducting preliminary data analysis. o	Conduct the thorough analysis of data to check for meaningful data. o	Perform data mining with using different querying techniques of SQL. o	Check for different data configurations and patterns. o	Help the senior management for decision making by representing the data with using different representational techniques like Graphs charts. o	Model the data with using different modeling techniques. o	Make the projections of the data according to analyzing the trends of data. o	Create different kind of reports with using different Business Intelligence tools like OBIEE or Tableau. o	Present your findings with good presentation through meetings, seminars and presentations. o	Preparing the report which will give information about all the data which will helps the senior management. o	Discuss with senior management about the 

In [34]:
#Count Vectorizer 
text_list = [resume2, jd]
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
count_matrix = cv.fit_transform(text_list)

In [35]:
from sklearn.metrics.pairwise import cosine_similarity
matchPercentage = cosine_similarity(count_matrix)
print(matchPercentage)

[[1.        0.5316244]
 [0.5316244 1.       ]]


In [36]:
# get the match percentage
matchPercentage = cosine_similarity(count_matrix)[0][1] * 100
matchPercentage = round(matchPercentage, 2) 
print("Your resume matches about "+ str(matchPercentage)+ "% of the job description.")

Your resume matches about 53.16% of the job description.


In [37]:
print(keywords(resume2, ratio =0.5))

data
machine learning
tree
engineering
language
modeling
model
models
present
florida
mining
statistics
programming
report ranking
regression related
scatter
project
computation
line
algorithm
multiline
capstone
artificial
box
customers based
architecture
developed
histogram plots
consultant
forest
naive
algebra
database
big
intelligence
structure
relevant
support


In [38]:
def jaccard_distance(resume2,jd):
    intersection=len(set.intersection(*[set(resume2),set(jd)]))
    union=len(set.union(*[set(resume2),set(jd)]))
    return intersection/float(union)
b=jaccard_distance(resume2,jd) 

print('\n  Jaccard  :  ', b)  


  Jaccard  :   0.6290322580645161


In [39]:
resume = docx2txt.process('/Users/akanshyameher/Desktop/Applicant5.docx')

In [40]:
#Summarizing resume 
text_resume = str(resume)
resume2 = summarize(text_resume, ratio=0.1)
print(resume2)

A Strong and passionate advocate of Data Science with 3+ years of hands-on experience leveraging machine learning models and data mining to uncover compelling insights and drive business growth.
Associate Data Analyst
Team member of AWS benchmarked Machine Learning project.
Led 5-person team and developed an e-commerce ETL application in 3 days using Python and Oracle.
Worked with the Data Science team in building an ML platform for an American Agriculture equipment manufacturing giant to increase the sales by recommending products after customer segmentation.
Utilized historical data on loans to predict the probability of a loan default by applying statistical methodologies to identify the association between attributes such as balance, income, occupation, etc.


In [41]:
#Prompt for the Job description.

jd = input("Enter the job description: ")  

Enter the job description: o	Collecting the data from multiple heterogeneous data sources. o	Check the actual nature of the data by conducting preliminary data analysis. o	Conduct the thorough analysis of data to check for meaningful data. o	Perform data mining with using different querying techniques of SQL. o	Check for different data configurations and patterns. o	Help the senior management for decision making by representing the data with using different representational techniques like Graphs charts. o	Model the data with using different modeling techniques. o	Make the projections of the data according to analyzing the trends of data. o	Create different kind of reports with using different Business Intelligence tools like OBIEE or Tableau. o	Present your findings with good presentation through meetings, seminars and presentations. o	Preparing the report which will give information about all the data which will helps the senior management. o	Discuss with senior management about the 

In [42]:
#Count Vectorizer 
text_list = [resume2, jd]
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
count_matrix = cv.fit_transform(text_list)

In [43]:
from sklearn.metrics.pairwise import cosine_similarity
matchPercentage = cosine_similarity(count_matrix)
print(matchPercentage)

[[1.         0.52250218]
 [0.52250218 1.        ]]


In [44]:
# get the match percentage
matchPercentage = cosine_similarity(count_matrix)[0][1] * 100
matchPercentage = round(matchPercentage, 2) 
print("Your resume matches about "+ str(matchPercentage)+ "% of the job description.")

Your resume matches about 52.25% of the job description.


In [45]:
print(keywords(resume2, ratio =0.5))

data
team
compelling
income
statistical
etl
leveraging machine learning
agriculture equipment manufacturing
business
segmentation
benchmarked
growth
utilized
recommending products
loans
passionate advocate
loan default
oracle


In [46]:
def jaccard_distance(resume2,jd):
    intersection=len(set.intersection(*[set(resume2),set(jd)]))
    union=len(set.union(*[set(resume2),set(jd)]))
    return intersection/float(union)
b=jaccard_distance(resume2,jd) 

print('\n  Jaccard  :  ', b)  


  Jaccard  :   0.6923076923076923


In [47]:
resume = docx2txt.process('/Users/akanshyameher/Desktop/Applicant6.docx')

In [48]:
#Summarizing resume 
text_resume = str(resume)
resume2 = summarize(text_resume, ratio=0.1)
print(resume2)

Python/AWS Developer	May 2018 – July 2019
Responsible for developing, maintaining and deploying web applications using Django,Python,MySQL
Wipro Limited, T-Mobile Project	Bangalore, India


In [49]:
#Prompt for the Job description.
jd = input("Enter the job description: ")  

Enter the job description: o	Collecting the data from multiple heterogeneous data sources. o	Check the actual nature of the data by conducting preliminary data analysis. o	Conduct the thorough analysis of data to check for meaningful data. o	Perform data mining with using different querying techniques of SQL. o	Check for different data configurations and patterns. o	Help the senior management for decision making by representing the data with using different representational techniques like Graphs charts. o	Model the data with using different modeling techniques. o	Make the projections of the data according to analyzing the trends of data. o	Create different kind of reports with using different Business Intelligence tools like OBIEE or Tableau. o	Present your findings with good presentation through meetings, seminars and presentations. o	Preparing the report which will give information about all the data which will helps the senior management. o	Discuss with senior management about the 

In [50]:
#Count Vectorizer 
text_list = [resume2, jd]
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
count_matrix = cv.fit_transform(text_list)

In [51]:
from sklearn.metrics.pairwise import cosine_similarity
matchPercentage = cosine_similarity(count_matrix)
print(matchPercentage)

[[1.         0.07212372]
 [0.07212372 1.        ]]


In [52]:
# get the match percentage
matchPercentage = cosine_similarity(count_matrix)[0][1] * 100
matchPercentage = round(matchPercentage, 2) 
print("Your resume matches about "+ str(matchPercentage)+ "% of the job description.")

Your resume matches about 7.21% of the job description.


In [53]:
print(keywords(resume2, ratio =0.5))

python
web
bangalore
project
wipro
developer
developing


In [54]:
def jaccard_distance(resume2,jd):
    intersection=len(set.intersection(*[set(resume2),set(jd)]))
    union=len(set.union(*[set(resume2),set(jd)]))
    return intersection/float(union)
b=jaccard_distance(resume2,jd) 

print('\n  Jaccard  :  ', b)  


  Jaccard  :   0.6071428571428571


In [55]:
resume = docx2txt.process('/Users/akanshyameher/Desktop/Applicant7.docx')

In [56]:
#Summarizing resume 
text_resume = str(resume)
resume2 = summarize(text_resume, ratio=0.1)
print(resume2)

Motivated, diligent and result oriented Programmer Analyst with 2.6 years of experience in Mobile Application development and ASP.Net. Proven ability to thrive in challenging, fast-paced environments through multi-tasking and organizational skills.
Sinhgad College of Engineering - Pune, Maharashtra, India Master of Engineering
http://linkedin.com/in/shrusharma


In [57]:
#Prompt for the Job description.
jd = input("Enter the job description: ")  

Enter the job description: o	Collecting the data from multiple heterogeneous data sources. o	Check the actual nature of the data by conducting preliminary data analysis. o	Conduct the thorough analysis of data to check for meaningful data. o	Perform data mining with using different querying techniques of SQL. o	Check for different data configurations and patterns. o	Help the senior management for decision making by representing the data with using different representational techniques like Graphs charts. o	Model the data with using different modeling techniques. o	Make the projections of the data according to analyzing the trends of data. o	Create different kind of reports with using different Business Intelligence tools like OBIEE or Tableau. o	Present your findings with good presentation through meetings, seminars and presentations. o	Preparing the report which will give information about all the data which will helps the senior management. o	Discuss with senior management about the 

In [58]:
#Count Vectorizer 
text_list = [resume2, jd]
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
count_matrix = cv.fit_transform(text_list)

In [59]:
from sklearn.metrics.pairwise import cosine_similarity
matchPercentage = cosine_similarity(count_matrix)
print(matchPercentage)

[[1.         0.15451992]
 [0.15451992 1.        ]]


In [60]:
# get the match percentage
matchPercentage = cosine_similarity(count_matrix)[0][1] * 100
matchPercentage = round(matchPercentage, 2) 
print("Your resume matches about "+ str(matchPercentage)+ "% of the job description.")

Your resume matches about 15.45% of the job description.


In [61]:
print(keywords(resume2, ratio =0.5))

application
oriented
programmer
proven
fast
sinhgad
skills
india
maharashtra
http
pune
engineering


In [62]:
def jaccard_distance(resume2,jd):
    intersection=len(set.intersection(*[set(resume2),set(jd)]))
    union=len(set.union(*[set(resume2),set(jd)]))
    return intersection/float(union)
b=jaccard_distance(resume2,jd) 

print('\n  Jaccard  :  ', b)  


  Jaccard  :   0.6153846153846154


In [63]:
resume = docx2txt.process('/Users/akanshyameher/Desktop/Applicant8.docx')

In [64]:
#Summarizing resume 
text_resume = str(resume)
resume2 = summarize(text_resume, ratio=0.1)
print(resume2)

Developed Front End (UI) for Cobertura - Impact based testing tool using AngularJS, HTML and CSS with data integration between MySQL database and application using Jersey REST web service.
Project: Real Time Object Tracking and Prediction, Noida, Jan 14 – May 14
Developed a real-time object tracking software using MATLAB followed by a prediction algorithm.
Utilized skills learned during the Data Science Specialization course.


In [65]:
#Prompt for the Job description.
jd = input("Enter the job description: ")  

Enter the job description: o	Collecting the data from multiple heterogeneous data sources. o	Check the actual nature of the data by conducting preliminary data analysis. o	Conduct the thorough analysis of data to check for meaningful data. o	Perform data mining with using different querying techniques of SQL. o	Check for different data configurations and patterns. o	Help the senior management for decision making by representing the data with using different representational techniques like Graphs charts. o	Model the data with using different modeling techniques. o	Make the projections of the data according to analyzing the trends of data. o	Create different kind of reports with using different Business Intelligence tools like OBIEE or Tableau. o	Present your findings with good presentation through meetings, seminars and presentations. o	Preparing the report which will give information about all the data which will helps the senior management. o	Discuss with senior management about the 

In [66]:
#Count Vectorizer 
text_list = [resume2, jd]
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
count_matrix = cv.fit_transform(text_list)

In [67]:
from sklearn.metrics.pairwise import cosine_similarity
matchPercentage = cosine_similarity(count_matrix)
print(matchPercentage)

[[1.         0.30588327]
 [0.30588327 1.        ]]


In [68]:
# get the match percentage
matchPercentage = cosine_similarity(count_matrix)[0][1] * 100
matchPercentage = round(matchPercentage, 2) 
print("Your resume matches about "+ str(matchPercentage)+ "% of the job description.")

Your resume matches about 30.59% of the job description.


In [69]:
print(keywords(resume2, ratio =0.5))

specialization
data
impact based testing
science
noida
tracking
utilized skills
rest web
prediction
algorithm
object
service


In [70]:
def jaccard_distance(resume2,jd):
    intersection=len(set.intersection(*[set(resume2),set(jd)]))
    union=len(set.union(*[set(resume2),set(jd)]))
    return intersection/float(union)
b=jaccard_distance(resume2,jd) 

print('\n  Jaccard  :  ', b)  


  Jaccard  :   0.7017543859649122


In [71]:
resume = docx2txt.process('/Users/akanshyameher/Desktop/Applicant9.docx')

In [72]:
#Summarizing resume 
text_resume = str(resume)
resume2 = summarize(text_resume, ratio=0.1)
print(resume2)

Proficient in skills like Python, R, Data Science, Statistical Analysis, Data Visualization and NLP.
Technical Skills: Python (Pandas, NumPy, Scikit-learn), R Programming, SAS, SQL, Machine Learning (CERTIFIED), Data Mining, Statistical Analysis, Distributed Technologies (Hadoop, Spark, Map Reduce), Google Analytics (CERTIFIED), Digital Marketing, VMWare, Linux, BASH, NLP.
UNIVERSITY OF CENTRAL FLORIDA   								Orlando-FL, USA Master of Science in Data Analytics							         


In [73]:
#Prompt for the Job description.
jd = input("Enter the job description: ")  

Enter the job description: o	Collecting the data from multiple heterogeneous data sources. o	Check the actual nature of the data by conducting preliminary data analysis. o	Conduct the thorough analysis of data to check for meaningful data. o	Perform data mining with using different querying techniques of SQL. o	Check for different data configurations and patterns. o	Help the senior management for decision making by representing the data with using different representational techniques like Graphs charts. o	Model the data with using different modeling techniques. o	Make the projections of the data according to analyzing the trends of data. o	Create different kind of reports with using different Business Intelligence tools like OBIEE or Tableau. o	Present your findings with good presentation through meetings, seminars and presentations. o	Preparing the report which will give information about all the data which will helps the senior management. o	Discuss with senior management about the 

In [74]:
#Count Vectorizer 
text_list = [resume2, jd]
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
count_matrix = cv.fit_transform(text_list)

In [75]:
from sklearn.metrics.pairwise import cosine_similarity
matchPercentage = cosine_similarity(count_matrix)
print(matchPercentage)

[[1.         0.30812955]
 [0.30812955 1.        ]]


In [76]:
# get the match percentage
matchPercentage = cosine_similarity(count_matrix)[0][1] * 100
matchPercentage = round(matchPercentage, 2) 
print("Your resume matches about "+ str(matchPercentage)+ "% of the job description.")

Your resume matches about 30.81% of the job description.


In [77]:
print(keywords(resume2, ratio =0.5))

data
certified
florida
nlp
skills
python
learning
analysis
analytics
statistical
sas
sql
master
usa
linux
bash
spark
vmware
hadoop


In [78]:
def jaccard_distance(resume2,jd):
    intersection=len(set.intersection(*[set(resume2),set(jd)]))
    union=len(set.union(*[set(resume2),set(jd)]))
    return intersection/float(union)
b=jaccard_distance(resume2,jd) 

print('\n  Jaccard  :  ', b)  


  Jaccard  :   0.6842105263157895


In [79]:
resume = docx2txt.process('/Users/akanshyameher/Desktop/Applicant10.docx')

In [80]:
#Summarizing resume 
text_resume = str(resume)
resume2 = summarize(text_resume, ratio=0.1)
print(resume2)

Coursework: Theory of Computation, Database Management Systems, Data Mining.
Worked on configurations in Salesforce Classic version, learnt Apex along with SOQL(Structured Object Query Language).
Worked as a Salesforce Developer(Classic Version along with nCino) focusing on Apex - Triggers, Batch classes.
My role in this project was to develop UI on Microsoft dotnet for servers and managing data using SQL.


In [81]:
#Prompt for the Job description.
jd = input("Enter the job description: ")  

Enter the job description: o	Collecting the data from multiple heterogeneous data sources. o	Check the actual nature of the data by conducting preliminary data analysis. o	Conduct the thorough analysis of data to check for meaningful data. o	Perform data mining with using different querying techniques of SQL. o	Check for different data configurations and patterns. o	Help the senior management for decision making by representing the data with using different representational techniques like Graphs charts. o	Model the data with using different modeling techniques. o	Make the projections of the data according to analyzing the trends of data. o	Create different kind of reports with using different Business Intelligence tools like OBIEE or Tableau. o	Present your findings with good presentation through meetings, seminars and presentations. o	Preparing the report which will give information about all the data which will helps the senior management. o	Discuss with senior management about the 

In [82]:
#Count Vectorizer 
text_list = [resume2, jd]
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
count_matrix = cv.fit_transform(text_list)

In [83]:
from sklearn.metrics.pairwise import cosine_similarity
matchPercentage = cosine_similarity(count_matrix)
print(matchPercentage)

[[1.         0.27149691]
 [0.27149691 1.        ]]


In [84]:
# get the match percentage
matchPercentage = cosine_similarity(count_matrix)[0][1] * 100
matchPercentage = round(matchPercentage, 2) 
print("Your resume matches about "+ str(matchPercentage)+ "% of the job description.")

Your resume matches about 27.15% of the job description.


In [85]:
print(keywords(resume2, ratio =0.5))

management
managing
classic
data
batch
object
triggers
query
database
apex
language
microsoft dotnet


In [86]:
def jaccard_distance(resume2,jd):
    intersection=len(set.intersection(*[set(resume2),set(jd)]))
    union=len(set.union(*[set(resume2),set(jd)]))
    return intersection/float(union)
b=jaccard_distance(resume2,jd) 

print('\n  Jaccard  :  ', b)  


  Jaccard  :   0.6792452830188679


In [87]:
cosine = [48.15,45.28,35.29,54.47,53.35,7.91,16.76,31.67,31.1,27.46]
jaccard = [69.64,58.06,63.93,63.90,69.23,60.71,61.53,70.17,68.42,67.92]

df= {'Applicant_Number':[1,2,3,4,5,6,7,8,9,10], 'Cosine': [48.15,45.28,35.29,54.47,53.35,7.91,16.76,31.67,31.1,27.46], 'Jaccard': [69.64,58.06,63.93,63.90,69.23,60.71,61.53,70.17,68.42,67.92]}
df

{'Applicant_Number': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 'Cosine': [48.15,
  45.28,
  35.29,
  54.47,
  53.35,
  7.91,
  16.76,
  31.67,
  31.1,
  27.46],
 'Jaccard': [69.64,
  58.06,
  63.93,
  63.9,
  69.23,
  60.71,
  61.53,
  70.17,
  68.42,
  67.92]}

In [88]:
import pandas as pd
pd.DataFrame(df)

Applicant_Number  Cosine  Jaccard
0                 1   48.15    69.64
1                 2   45.28    58.06
2                 3   35.29    63.93
3                 4   54.47    63.90
4                 5   53.35    69.23
5                 6    7.91    60.71
6                 7   16.76    61.53
7                 8   31.67    70.17
8                 9   31.10    68.42
9                10   27.46    67.92